export const studyPlans = {
  1: [
    {
      subjectName: "Algoritmia e Estruturas de Dados",
      semester: 1,
      ectsCount: 7,
      info: "Aprende os conceitos básicos de algoritmos, como notação algorítmica e estruturas de controlo. Implementa algoritmos em Python, trabalha com decomposição modular e tipos de dados avançados. Desenvolve aplicações com interface gráfico usando a biblioteca tkinter.",
    },
    {
      subjectName: "Fundamentos de Design",
      semester: 1,
      ectsCount: 6,
      info: "Aprende a identificar e analisar elementos gráficos em design e web design. Estuda tipografia, cor, iconografia e grelhas, e aplica esses conhecimentos em projetos práticos.",
    },
    {
      subjectName: "Matemática I",
      semester: 1,
      ectsCount: 5,
      info: "Desenvolve a capacidade de raciocínio lógico estruturado e aplicação criativa de técnicas de cálculo. Estuda lógica, teoria de conjuntos e cálculo integral, focando na resolução de problemas.",
    },
    {
      subjectName: "Sistemas Computacionais",
      semester: 1,
      ectsCount: 5,
      info: "Estuda arquiteturas computacionais, sistemas digitais baseados no sistema binário e programação de sistemas digitais simples. Inclui introdução às redes de computadores e sistemas embebidos, como Arduino e sensores.",
    },
    {
      subjectName: "Tecnologias Web",
      semester: 1,
      ectsCount: 7,
      info: "Estuda HTML5 e CSS para criar e estilizar páginas Web, usa Bootstrap para sites responsivos, e aplica linguagens de scripting para tornar as aplicações Web dinâmicas e interativas.",
    },
    {
      subjectName: "Conceção e Produção Multimédia",
      semester: 2,
      ectsCount: 5,
      info: "Explora tipos de informação multimédia, análise de produtos, planeamento, conceção de aplicações e narrativas interativas, e utiliza plataformas digitais e WebVR.",
    },
    {
      subjectName: "Interfaces e Design para Aplicações",
      semester: 2,
      ectsCount: 6,
      info: "Explora o design centrado no utilizador, incluindo princípios digitais técnicos e metodologias de trabalho.  Estuda conceitos fundamentais de experiência do utilizador (UX), wireframing, tipos de interface e tecnologias utilizadas, design de interfaces e usabilidade.",
    },
    {
      subjectName: "Matemática II",
      semester: 2,
      ectsCount: 5,
      info: "Explora álgebra linear, incluindo matrizes, operações, determinantes e sistemas de equações lineares. Estuda também geometria analítica, abordando espaços afins, posições relativas no plano e no espaço, e construção de superfícies de revolução.",
    },
    {
      subjectName: "Programação Orientada a Objetos",
      semester: 2,
      ectsCount: 7,
      info: "Desenvolve competências em JavaScript, manipulação da DOM, objetos e arrays, classes e estruturação de uma aplicação web seguindo o padrão MVC adaptado.",
    },
    {
      subjectName: "Projeto I",
      semester: 2,
      ectsCount: 7,
      info: "Promove a interdisciplinaridade e desenvolve competências na criação, gestão e desenvolvimento de projetos informáticos.",
    },
  ],
  2: [
    {
      subjectName: "Bases de Dados",
      semester: 1,
      ectsCount: 5,
      info: " Explora modelagem, normalização e implementação de bases de dados relacionais e não relacionais. Aborda o modelo relacional e a normalização, implementação em MySQL, linguagem SQL, administração e segurança de bases de dados, além de introdução ao NoSQL com foco em MongoDB.",
    },
    {
      subjectName: "Computação Gráfica",
      semester: 1,
      ectsCount: 7,
      info: "Explora os conceitos básicos de animação gráfica (2D), computação gráfica (3D) e interação na Web. Utiliza a biblioteca Three.js para criar cenas 3D interativas, incluindo cenas, câmeras, objetos, materiais, texturas, luzes e sombras.",
    },
    {
      subjectName: "Engenharia de Software",
      semester: 1,
      ectsCount: 6,
      info: "Explora a engenharia de requisitos, desenho de software e desenvolvimento de qualidade de sistemas de informação. Inclui ciclo de vida do software, metodologias e técnicas de desenvolvimento, integração contínua, gestão de versões, verificação e validação de software, testes, revisões e análise estática de código.",
    },
    {
      subjectName: "Ergonomia Cognitiva e Design de Interação",
      semester: 1,
      ectsCount: 5,
      info: "Aborda conceitos fundamentais de design de interação, usabilidade, UI e UX. Inclui técnicas de concepção e prototipagem de projetos digitais, idealização, planeamento, desenho de interfaces web, prototipagem e avaliação de interfaces.",
    },
    {
      subjectName: "Programação Web I",
      semester: 1,
      ectsCount: 7,
      info: "Explora os principais protocolos, padrões, linguagens, frameworks e ferramentas usadas na programação para a web; routing, gestão de estado com Vue.js, invocação de APIs para tornar as aplicações mais dinâmicas, e introdução aos testes em Vue.js com o Vitest",
    },
    {
      subjectName: "Inteligência Artificial",
      semester: 2,
      ectsCount: 6,
      info: "Abrange os conceitos fundamentais de Inteligência Artificial (IA), incluindo algoritmos de Machine Learning, tipos de aprendizado automático e sua aplicação em diferentes domínios, como processamento de linguagem natural e assistentes virtuais. Os alunos também aprendem Python e suas bibliotecas essenciais para IA.",
    },
    {
      subjectName: "Programação Web II",
      semester: 2,
      ectsCount: 7,
      info: "Aprofunda o conhecimento sobre arquitetura MVC (Model-View-Controller) e o desenvolvimento de aplicações web multiplataforma. Aprende sobre serviços web, incluindo o paradigma CRUD e a criação de APIs RESTful.",
    },
    {
      subjectName: "Projeto II",
      semester: 2,
      ectsCount: 6,
      info: "O projeto integra as diferentes unidades curriculares, permitindo aos alunos gerir projetos de desenvolvimento web e dominar a virtualização para configurar máquinas virtuais.",
    },
    {
      subjectName: "Testes e Performance Web",
      semester: 2,
      ectsCount: 6,
      info: "Serão lecionadas métricas de performance, ferramentas de avaliação, otimização de código e recursos, além de compreender a importância e os tipos de testes. Serão abordadas estratégias de testes, automação e integração contínua.",
    },
    {
      subjectName: "Análise de Filmes (opcional)",
      semester: 2,
      ectsCount: 5,
    },
    {
      subjectName: "Cultura Digital (opcional)",
      semester: 2,
      ectsCount: 5,
      info: "Aborda os fundamentos teóricos da cultura digital, explorando a relação entre desenvolvimento humano e sistemas digitais. Os alunos aprendem sobre criação digital, novos paradigmas de autoria e os impactos da comunicação multimédia na sociedade",
    },
    {
      subjectName: "Laboratório I (opcional)",
      semester: 2,
      ectsCount: 5,
    },
    {
      subjectName: "Laboratório II (opcional)",
      semester: 2,
      ectsCount: 5,
    },
    {
      subjectName: "Programação I (opcional)",
      semester: 2,
      ectsCount: 5,
    },
    {
      subjectName: "Programação III (opcional)",
      semester: 2,
      ectsCount: 5,
      info: "Os tópicos incluem introdução à arte digital, programação, animação gráfica, conteúdos multimédia, audiovisuais generativos, métodos de animação, física, visão por computador e interação.",
    },
    {
      subjectName: "Publicação e Divulgação em Media Digitais (opcional)",
      semester: 2,
      ectsCount: 5,
    },
    {
      subjectName: "Som (opcional)",
      semester: 2,
      ectsCount: 5,
      info: "Os alunos aprenderão sobre os princípios do som, operação de equipamentos de áudio e uso de software de edição de som.",
    },
    {
      subjectName: "Som e Imagem (opcional)",
      semester: 2,
      ectsCount: 5,
      info: "Os alunos aprenderão a criar, capturar e editar som e imagem, explorando suas propriedades físicas e estéticas. O módulo de som abrange noções básicas das propriedades físicas, percepção e cognição, além de técnicas de captação, edição e mixagem de som.",
    },
    {
      subjectName: "Som I (opcional)",
      semester: 2,
      ectsCount: 5,
      info: "Os tópicos lecionados incluem teoria e prática do registo de vídeo, composição de imagem e movimentos de câmara, princípios de iluminação, e narrativa audiovisual com ênfase em storyboards e planificação técnica.",
    },
    {
      subjectName: "Teoria e Análise da Imagem (opcional)",
      semester: 2,
      ectsCount: 5,
      info: " A comunicação visual e semiótica são temas centrais, incluindo a análise de elementos significativos, como intenção, comunicação, significado e referência. ",
    },
  ],
  3: [
    {
      subjectName: "Computação Móvel e Ubíqua",
      semester: 1,
      ectsCount: 6,
      info: "A unidade curricular foca no desenvolvimento de competências para criar e manter aplicações web usando a framework React, e aplicações móveis híbridas para Android e iOS usando a framework React Native.",
    },
    {
      subjectName: "Inovação e Empreendedorismo",
      semester: 1,
      ectsCount: 5,
      info: "Os tópicos abordados incluem conceitos de empreendedorismo, cultura empreendedora, criatividade, inovação, modelos e planos de negócios, bem como implementação e desenvolvimento de projetos.",
    },
    {
      subjectName: "Negócio Eletrónico e Segurança",
      semester: 1,
      ectsCount: 6,
      info: " As competências gerais incluem a compreensão das oportunidades e riscos do comércio eletrónico, a elaboração de modelos de negócio eletrónico seguro e a avaliação da segurança da informação e sistemas.",
    },
    {
      subjectName: "Prototipagem Avançada em Plataformas Digitais",
      semester: 1,
      ectsCount: 6,
      info: "A unidade curricular visa capacitar os alunos para aplicar conceitos de Design Gráfico e UI Design na estilização e prototipagem de interfaces com base na lógica UX.",
    },
    {
      subjectName: "Serviços e Interfaces para a Cloud",
      semester: 1,
      ectsCount: 7,
      info: "Os alunos adquirem competências como compreender arquiteturas de sistemas distribuídos, criar serviços web REST e GraphQL, e fazer o deploy de serviços na cloud.",
    },
    {
      subjectName: "Marketing Digital",
      semester: 2,
      ectsCount: 3,
      info: "Explora estratégias de marketing de conteúdo e os principais canais digitais, como websites, SEO, email marketing e redes sociais.",
    },
    {
      subjectName: "Projeto Final/Estágio",
      semester: 2,
      ectsCount: 2,
      info: "O Projeto Final ou Estágio representa a culminação do curso, visando preparar os alunos para o mercado de trabalho.",
    },
    {
      subjectName: "Usabilidade e User Experience",
      semester: 2,
      ectsCount: 4,
      info: "Os alunos aprenderão diferentes metodologias de desenvolvimento centradas no usuário, incluindo técnicas de pesquisa de usuário, planejamento e avaliação de UX. A ênfase será na elaboração de documentação abrangente para descrever o planejamento, execução e avaliação das práticas de UX adotadas.",
    },
  ],
};
